// Tipos centralizados para el Taller CAD
import { CircuitInventoryItemForCAD } from '../lib/electrical-rules';
import type { Floor } from './floors';

export type SymbolType =
    // Símbolos de Planta
    | 'light' | 'wall_light' | 'outlet' | 'double_outlet'
    | 'switch' | 'switch_2e' | 'switch_3e' | 'switch_3way' | 'bell_button'
    | 'motion_sensor' | 'photo_cell' | 'riser'
    | 'cp' | 'ac' | 'fan' | 'motor_1p' | 'motor_3p'
    | 'board' | 'tpu' | 'ground'
    // Símbolos Unifilares — Alimentación
    | 'meter'
    // Símbolos Unifilares — Líneas y Circuitos
    | 'lp_220' | 'lp_380' | 'cs_220' | 'cs_380' | 'ct_220' | 'ct_380'
    // Símbolos Unifilares — Borneras
    | 'dist_block' | 'dist_block_2' | 'dist_block_3' | 'dist_block_4' | 'dist_block_5'
    | 'dist_block_6' | 'dist_block_7' | 'dist_block_8' | 'dist_block_9' | 'dist_block_10'
    // Símbolos Unifilares — Protecciones
    | 'pia_1p' | 'pia_3p'
    | 'diff_switch' | 'id_3p'
    // Símbolos Unifilares — Motores y arranque
    | 'gm_thermo' | 'gm_mag' | 'contactor' | 'thermal_relay'
    // Símbolos Unifilares — Legacy (compatibilidad)
    | 'load_arrow'
    // Especiales
    | 'text' | 'table' | 'rect' | 'circle' | 'triangle' | 'line' | 'arrow';

export type TradeCategory = 'electrical' | 'gas' | 'plumbing';

// 🆕 LayerId ahora soporta IDs dinámicos de circuitos además de las capas fijas
export type LayerId = string; // Puede ser 'layer-0' (arquitectura), 'layer-N' (circuito), etc.

export interface SymbolDefinition {
    id: SymbolType;
    name: string;
    category: TradeCategory;
    svgPath: string;
    strokeColor: string;
    fillColor?: string;
    // Embedded text elements that are part of the symbol's graphic
    // (e.g. 'kWh' inside meter, 'Ɪ>' inside guarda motor)
    textElements?: Array<{
        text: string;
        x: number;
        y: number;
        fontSize: number;
        width?: number; // Para centrado automático
        align?: 'left' | 'center' | 'right';
        fill?: string;
        fontStyle?: string; // 'bold' | 'italic' etc.
    }>;
    metadata: {
        description: string;
        normative?: string; // Ej: "AEA 90364-7-771"
        defaultLabel?: string;
    };
}

export interface SymbolItem {
    id: string;
    type: SymbolType;
    x: number;
    y: number;
    rotation: number;
    scaleX?: number;
    scaleY?: number;
    label?: string;
    color?: string;
    fontSize?: number;
    layer?: LayerId;
    points?: number[]; // 🆕 Para geometrías basadas en puntos (línea, flecha)
    nature?: 'relevado' | 'proyectado'; // 🆕 NATURALEZA

    // 🆕 Circuit data (heredado de la capa)
    circuitId?: string; // ID del circuito (ej: "TP-IUG-1")

    // 🆕 Auto-generación
    autoGenerated?: boolean; // Flag para elementos generados automáticamente

    // 🆕 Propiedades de Geometría
    fill?: string;
    strokeDash?: number[];
    isSolid?: boolean;
    lineType?: 'solid' | 'dashed' | 'dotted' | 'symmetry';
}

export interface Wall {
    id: string;
    points: number[];
    layer?: LayerId;
    nature?: 'relevado' | 'proyectado'; // 🆕 NATURALEZA

    // 🆕 Circuit data (para elementos arquitectónicos no aplica)
    circuitId?: string;
}

export interface Pipe {
    id: string;
    points: number[];
    color: string;
    type: 'straight' | 'curved';
    controlPoint?: { x: number; y: number }; // 🆕 Punto de control para curvas (novedad)
    layer?: LayerId;
    nature?: 'relevado' | 'proyectado'; // 🆕 NATURALEZA

    // 🆕 Circuit data (heredado de la capa)
    circuitId?: string; // ID del circuito que representa este caño
}

export interface AuxLine {
    id: string;
    points: number[];
    layer?: LayerId;
}

export interface Layer {
    id: LayerId;
    name: string;
    visible: boolean;
    locked: boolean;
    opacity: number;
    color: string;

    // 🆕 Circuit-based layer data
    circuitId?: string | null; // null para capa arquitectura, string para capas de circuito
    circuit?: CircuitInventoryItemForCAD; // Datos completos del circuito (cable, protección, conduit)
}

export interface ProjectData {
    projectName: string;
    address: string;
    installer: string;
    category: string;
    date: string;
}

export interface DrawingData {
    // Formato nuevo (unificado) - ambos modos comparten el mismo canvas
    floors?: Floor[];
    pixelsPerMeter?: number;

    // Formato antiguo (dual-mode) - para compatibilidad con proyectos existentes
    floorPlan?: {
        symbols?: SymbolItem[];
        walls?: Wall[];
        pipes?: Pipe[];
        auxLines?: AuxLine[];
        pixelsPerMeter?: number;
        floors?: Floor[];
    };
    singleLine?: {
        symbols?: SymbolItem[];
        walls?: Wall[];
        pipes?: Pipe[];
        auxLines?: AuxLine[];
        pixelsPerMeter?: number;
        floors?: Floor[];
    };
    backgroundBase64?: string | null;
    backgroundProps?: {
        x: number;
        y: number;
        scaleX: number;
        scaleY: number;
        rotation: number;
    };
}

export interface MaterialReport {
    counts: Record<string, number>;
    totalPipeMeters: number;
    totalCableMeters: number;
}

export interface TradeCatalog {
    id: string;
    name: string;
    version: string;
    symbols: SymbolDefinition[];
    calculations: {
        materials: (symbols: SymbolItem[], pipes: Pipe[], pixelsPerMeter: number) => MaterialReport;
        loads?: (symbols: SymbolItem[]) => any;
    };
}
